checks:
    php: true
filter:
    excluded_paths: [vendor/*, tests/*, src/EnvSyncServiceProvider.php]
coding_style:
    php: {  }
tools:
    php_code_coverage: true
build:
    nodes:
        coverage:
            tests:
                override:
                    - command: ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
                      coverage:
                          file: coverage.clover   # <- Set this to where we find the coverage data.
                          #    The path is relative to the current directory.
                          format: clover
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
